global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: forgeops-api
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8080"]

  - job_name: forgeops-worker
    static_configs:
      - targets: ["worker:9102"]
